// @generated
// This file was automatically generated and should not be edited.

@_exported import ApolloAPI

public class AllTasksQuery: GraphQLQuery {
  public static let operationName: String = "AllTasks"
  public static let document: ApolloAPI.DocumentType = .notPersisted(
    definition: .init(
      #"""
      query AllTasks {
        tasks {
          __typename
          id
          name
          completed
          user {
            __typename
            id
            name
          }
        }
      }
      """#
    ))

  public init() {}

  public struct Data: GraphiOSAutogenerated.SelectionSet {
    public let __data: DataDict
    public init(data: DataDict) { __data = data }

    public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.Query }
    public static var __selections: [ApolloAPI.Selection] { [
      .field("tasks", [Task]?.self),
    ] }

    public var tasks: [Task]? { __data["tasks"] }

    /// Task
    ///
    /// Parent Type: `Task`
    public struct Task: GraphiOSAutogenerated.SelectionSet {
      public let __data: DataDict
      public init(data: DataDict) { __data = data }

      public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.Task }
      public static var __selections: [ApolloAPI.Selection] { [
        .field("id", GraphiOSAutogenerated.ID.self),
        .field("name", String.self),
        .field("completed", Bool.self),
        .field("user", User.self),
      ] }

      public var id: GraphiOSAutogenerated.ID { __data["id"] }
      public var name: String { __data["name"] }
      public var completed: Bool { __data["completed"] }
      public var user: User { __data["user"] }

      /// Task.User
      ///
      /// Parent Type: `User`
      public struct User: GraphiOSAutogenerated.SelectionSet {
        public let __data: DataDict
        public init(data: DataDict) { __data = data }

        public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.User }
        public static var __selections: [ApolloAPI.Selection] { [
          .field("id", GraphiOSAutogenerated.ID.self),
          .field("name", String.self),
        ] }

        public var id: GraphiOSAutogenerated.ID { __data["id"] }
        public var name: String { __data["name"] }
      }
    }
  }
}
