// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "GraphClientPackage",
    platforms: [
        .iOS(.v15),
        .macOS(.v12)
    ],
    products: [
        .library(
            name: "GraphClientPackage",
            targets: ["GraphClientPackage"]),
    ],
    dependencies: [
        .package(
            url: "https://github.com/apollographql/apollo-ios.git",
            .upToNextMajor(from: "1.0.6")
        ),
//        .package(
//            url: "https://github.com/apple/swift-collections.git",
//            .upToNextMajor(from: "1.0.4")
//        ),
        .package(path: "../GraphiOSAutogenerated")
    ],
    targets: [
        .target(
            name: "GraphClientPackage",
            dependencies: [
                .product(name: "Apollo", package: "apollo-ios"),
                "GraphiOSAutogenerated"
            ]
        ),
        .testTarget(
            name: "GraphClientPackageTests",
            dependencies: ["GraphClientPackage"]
        ),
    ]
)
