// @generated
// This file was automatically generated and should not be edited.

@_exported import ApolloAPI

public class TaskByIDQuery: GraphQLQuery {
  public static let operationName: String = "TaskByID"
  public static let document: ApolloAPI.DocumentType = .notPersisted(
    definition: .init(
      #"""
      query TaskByID($id: ID!) {
        task(id: $id) {
          __typename
          id
          name
          completed
        }
      }
      """#
    ))

  public var id: ID

  public init(id: ID) {
    self.id = id
  }

  public var __variables: Variables? { ["id": id] }

  public struct Data: GraphiOSAutogenerated.SelectionSet {
    public let __data: DataDict
    public init(data: DataDict) { __data = data }

    public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.Query }
    public static var __selections: [ApolloAPI.Selection] { [
      .field("task", Task?.self, arguments: ["id": .variable("id")]),
    ] }

    public var task: Task? { __data["task"] }

    /// Task
    ///
    /// Parent Type: `Task`
    public struct Task: GraphiOSAutogenerated.SelectionSet {
      public let __data: DataDict
      public init(data: DataDict) { __data = data }

      public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.Task }
      public static var __selections: [ApolloAPI.Selection] { [
        .field("id", GraphiOSAutogenerated.ID.self),
        .field("name", String.self),
        .field("completed", Bool.self),
      ] }

      public var id: GraphiOSAutogenerated.ID { __data["id"] }
      public var name: String { __data["name"] }
      public var completed: Bool { __data["completed"] }
    }
  }
}
