// @generated
// This file was automatically generated and should not be edited.

@_exported import ApolloAPI

public class UserWithTasksByIDQuery: GraphQLQuery {
  public static let operationName: String = "UserWithTasksByID"
  public static let document: ApolloAPI.DocumentType = .notPersisted(
    definition: .init(
      #"""
      query UserWithTasksByID($id: ID!) {
        user(id: $id) {
          __typename
          id
          name
          email
          tasks {
            __typename
            id
            name
            completed
          }
        }
      }
      """#
    ))

  public var id: ID

  public init(id: ID) {
    self.id = id
  }

  public var __variables: Variables? { ["id": id] }

  public struct Data: GraphiOSAutogenerated.SelectionSet {
    public let __data: DataDict
    public init(data: DataDict) { __data = data }

    public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.Query }
    public static var __selections: [ApolloAPI.Selection] { [
      .field("user", User?.self, arguments: ["id": .variable("id")]),
    ] }

    public var user: User? { __data["user"] }

    /// User
    ///
    /// Parent Type: `User`
    public struct User: GraphiOSAutogenerated.SelectionSet {
      public let __data: DataDict
      public init(data: DataDict) { __data = data }

      public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.User }
      public static var __selections: [ApolloAPI.Selection] { [
        .field("id", GraphiOSAutogenerated.ID.self),
        .field("name", String.self),
        .field("email", String.self),
        .field("tasks", [Task]?.self),
      ] }

      public var id: GraphiOSAutogenerated.ID { __data["id"] }
      public var name: String { __data["name"] }
      public var email: String { __data["email"] }
      public var tasks: [Task]? { __data["tasks"] }

      /// User.Task
      ///
      /// Parent Type: `Task`
      public struct Task: GraphiOSAutogenerated.SelectionSet {
        public let __data: DataDict
        public init(data: DataDict) { __data = data }

        public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.Task }
        public static var __selections: [ApolloAPI.Selection] { [
          .field("id", GraphiOSAutogenerated.ID.self),
          .field("name", String.self),
          .field("completed", Bool.self),
        ] }

        public var id: GraphiOSAutogenerated.ID { __data["id"] }
        public var name: String { __data["name"] }
        public var completed: Bool { __data["completed"] }
      }
    }
  }
}
