// @generated
// This file was automatically generated and should not be edited.

@_exported import ApolloAPI

public class UserByIDQuery: GraphQLQuery {
  public static let operationName: String = "UserByID"
  public static let document: ApolloAPI.DocumentType = .notPersisted(
    definition: .init(
      #"""
      query UserByID($id: ID!) {
        user(id: $id) {
          __typename
          id
          name
          email
        }
      }
      """#
    ))

  public var id: ID

  public init(id: ID) {
    self.id = id
  }

  public var __variables: Variables? { ["id": id] }

  public struct Data: GraphiOSAutogenerated.SelectionSet {
    public let __data: DataDict
    public init(data: DataDict) { __data = data }

    public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.Query }
    public static var __selections: [ApolloAPI.Selection] { [
      .field("user", User?.self, arguments: ["id": .variable("id")]),
    ] }

    public var user: User? { __data["user"] }

    /// User
    ///
    /// Parent Type: `User`
    public struct User: GraphiOSAutogenerated.SelectionSet {
      public let __data: DataDict
      public init(data: DataDict) { __data = data }

      public static var __parentType: ApolloAPI.ParentType { GraphiOSAutogenerated.Objects.User }
      public static var __selections: [ApolloAPI.Selection] { [
        .field("id", GraphiOSAutogenerated.ID.self),
        .field("name", String.self),
        .field("email", String.self),
      ] }

      public var id: GraphiOSAutogenerated.ID { __data["id"] }
      public var name: String { __data["name"] }
      public var email: String { __data["email"] }
    }
  }
}
